### ISSUE TITLE
Improve text definitions

### ISSUE THREAD

**Issue by dosumis** [Cellular-Semantics/whole_human_brain_ontology#20]
- Genus in text definitions of data-linked classes is driven by config specification of root nodes.
This leads to some odd looking cases where a very specific cell types for which we have a classification but a very generic genus in the text definition: e.g. 

<img width="500" alt="image" src="https://github.com/hkir-dev/whole_human_brain_ontology/assets/112839/34cc653d-57b4-4c0c-84a4-b7e9400523dd">

I think better to be able to utilise the more specific classification in the curation table.  I don't recall why we don't do this as the curation table is DOSDP and so should be accessible to text generation.

**Comment by dosumis** [comment]
A major reason we've added so many "root" terms in the config is to (partly) get around this issue.

**Comment by hkir-dev** [comment]
Curation table is accessible to text generation. But we don't have if logic in dospd, so we cannot say if `Classification` defined use it, otherwise use `Gross_cell_type`. So I will add gross classifications to the `Classification` column if a more specific classification is not defined. Then I will use `Classification` to roll descriptions (and label & synonyms as well?)

**Comment by dosumis** [comment]
Sounds good.

**Comment by hkir-dev** [comment]
New label: `URL_308 unipolar brush cell (Hsap)`
New desc: `A unipolar brush cell of the Homo sapiens brain. These cells can be distinguished from other cells in the brain by their selective expression of EOMES (Hsap), RP11-312A15.5 (Hsap). The soma of these cells can be found in the cerebellum, pons. The reference data for this cell type is CS202210140_309.`
